name: publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          zip -r resources.zip assets pack.mcmeta pack.png

      - name: Calculate hash of resource.zip
        id: calculate-hash
        run: |
          sha256sum resources.zip | awk '{ print $1 }' > hash.txt

      - name: Commit and push hash.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add hash.txt
          git commit -m "Update hash.txt with new hash"
          git push origin main:hash --force

      - name: latest-release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          files: "resources.zip"
